# Generated by Django 3.0.8 on 2020-08-17 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20200815_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
